### ISSUE TITLE
Error when parsing email without attachment info

### ISSUE THREAD

**Issue by fabiokr** [kamilc/mailman#26]
I get this error when trying to parse an email without attachment info:

Example email: https://gist.github.com/fabiokr/13639921d958d3949cfb

```
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        lib/mailman/parsing.ex:58: Mailman.Parsing.filename_from_raw/1
        lib/mailman/parsing.ex:74: Mailman.Parsing.is_raw_attachement/1
        (elixir) lib/enum.ex:704: anonymous fn/3 in Enum.filter/2
        (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
        (elixir) lib/enum.ex:704: Enum.filter/2
        lib/mailman/parsing.ex:89: Mailman.Parsing.get_attachments/1
        lib/mailman/parsing.ex:17: Mailman.Parsing.parse/1
        lib/mailman/parsing.ex:5: Mailman.Parsing.parse/1
        lib/mailman/parsing.ex:26: Mailman.Parsing.parse!/1
```

**Comment by Gidrek** [comment]
I have to add mime type in my case

**Comment by kin9puppy** [comment]
Interested to see the answer here as well.
