### ISSUE TITLE
Mix test - 2 tests fail

### ISSUE THREAD

**Issue by daneb** [kamilc/mailman#8]
Good 

Thanks again for your effort here.
In trying to resolve my prior logged issue, I pulled the latest repo and had 2 unit tests fail.

```
  1) test sending testing emails works (MailmanTest)
     test/mailman_test.exs:66
     ** (UndefinedFunctionError) undefined function: :eiconv.open/2 (module :eiconv is not available)
     stacktrace:
       (eiconv) :eiconv.open("utf-8//IGNORE", "utf-8")
       (gen_smtp) src/mimemail.erl:477: :mimemail.decode_body/4
       (gen_smtp) src/mimemail.erl:268: :mimemail.decode_component/4
       (gen_smtp) src/mimemail.erl:386: :mimemail."-split_body_by_boundary/4-lc$^1/1-0-"/3
       (gen_smtp) src/mimemail.erl:259: :mimemail.decode_component/4
       (mailman) lib/mailman/parsing.ex:5: Mailman.Parsing.parse/1
       test/mailman_test.exs:68



  2) test encodes attachements properly (MailmanTest)
     test/mailman_test.exs:75
     ** (UndefinedFunctionError) undefined function: :eiconv.open/2 (module :eiconv is not available)
     stacktrace:
       (eiconv) :eiconv.open("utf-8//IGNORE", "us-ascii")
       (gen_smtp) src/mimemail.erl:477: :mimemail.decode_body/4
       (gen_smtp) src/mimemail.erl:268: :mimemail.decode_component/4
       (gen_smtp) src/mimemail.erl:386: :mimemail."-split_body_by_boundary/4-lc$^1/1-0-"/3
       (gen_smtp) src/mimemail.erl:259: :mimemail.decode_component/4
       (mailman) lib/mailman/parsing.ex:5: Mailman.Parsing.parse/1
       (mailman) lib/mailman/parsing.ex:26: Mailman.Parsing.parse!/1
       test/mailman_test.exs:77
```

Is this me or legitimate issues?

Thanks
Dane

**Comment by kamilc** [comment]
@daneb Yes, that's supposed to be like that **for now** as there's no eiconv package in Hex currently... Take a look at this part of README: https://github.com/kamilc/mailman#using-with-hex
